services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - STORAGE_PATH=/app/storage
      - DEBUG=false
    volumes:
      - ./storage:/app/storage
    networks:
      - bot_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bot_network:
    driver: bridge